In [7]:
!pip install gensim

You should consider upgrading via the '/Users/binod/Documents/software/anaconda/anaconda3/bin/python -m pip install --upgrade pip' command.


In [8]:
#This code on how to generate word embedding of a word from given sentence
from gensim.models import Word2Vec
from sklearn.metrics.pairwise import cosine_similarity

# Define the example sentences
sentences = [
    "The puppy loyal to its owner and loved to chase its tail",
    "The dog was loyal and protective of its owner, has lovely tail"
]


# Split the sentences into lists of words
word_lists = [sentence.lower().split() for sentence in sentences]
word_lists

[['the',
  'puppy',
  'loyal',
  'to',
  'its',
  'owner',
  'and',
  'loved',
  'to',
  'chase',
  'its',
  'tail'],
 ['the',
  'dog',
  'was',
  'loyal',
  'and',
  'protective',
  'of',
  'its',
  'owner,',
  'has',
  'lovely',
  'tail']]

In [9]:
# Train the Word2Vec model on the example sentences
model = Word2Vec(word_lists, min_count=1)

# Get the embeddings for "associate" and "employee"
embedding_1 = model.wv['puppy']
embedding_2 = model.wv['dog']

# Print the embeddings
print("Embedding for 'puppy': ", embedding_1)
print("Embedding for 'dog': ", embedding_2)

Embedding for 'puppy':  [ 8.1693530e-03 -4.4424967e-03  8.9852214e-03  8.2536135e-03
 -4.4353902e-03  3.0241191e-04  4.2745322e-03 -3.9266776e-03
 -5.5602933e-03 -6.5135299e-03 -6.6985562e-04 -2.9506299e-04
  4.4629988e-03 -2.4744093e-03 -1.7139514e-04  2.4623820e-03
  4.8689600e-03 -3.1117946e-05 -6.3400054e-03 -9.2621362e-03
  2.6943893e-05  6.6615203e-03  1.4670712e-03 -8.9669479e-03
 -7.9381913e-03  6.5520909e-03 -3.7867506e-03  6.2539754e-03
 -6.6802753e-03  8.4803579e-03 -6.5157204e-03  3.2886867e-03
 -1.0567167e-03 -6.7876372e-03 -3.2876898e-03 -1.1616098e-03
 -5.4721525e-03 -1.2111445e-03 -7.5635971e-03  2.6450334e-03
  9.0694204e-03 -2.3773636e-03 -9.7476749e-04  3.5129883e-03
  8.6645139e-03 -5.9219110e-03 -6.8874871e-03 -2.9331418e-03
  9.1473395e-03  8.6730585e-04 -8.6782174e-03 -1.4478377e-03
  9.4779180e-03 -7.5491238e-03 -5.3589093e-03  9.3162311e-03
 -8.9734495e-03  3.8262166e-03  6.6430384e-04  6.6604549e-03
  8.3128037e-03 -2.8500976e-03 -3.9914288e-03  8.8984985e-03


In [10]:
embedding_1.shape

(100,)

In [11]:
similarity = cosine_similarity(embedding_1.reshape(1,-1), embedding_2.reshape(1,-1))[0][0]

print("Cosine similarity : ", similarity)

Cosine similarity :  0.11131189


"word2vec-google-news-300" is a pre-trained word embedding model developed by Google which contains word vectors for more than 3 million words and phrases. The vectors in this model were trained on a large dataset of news articles and have 300 dimensions.

In [12]:
import gensim.downloader as api

# Load a pre-trained Word2Vec model using the Gensim downloader
model = api.load("word2vec-google-news-300")

In [13]:
dog = model['dog']
dog

array([ 5.12695312e-02, -2.23388672e-02, -1.72851562e-01,  1.61132812e-01,
       -8.44726562e-02,  5.73730469e-02,  5.85937500e-02, -8.25195312e-02,
       -1.53808594e-02, -6.34765625e-02,  1.79687500e-01, -4.23828125e-01,
       -2.25830078e-02, -1.66015625e-01, -2.51464844e-02,  1.07421875e-01,
       -1.99218750e-01,  1.59179688e-01, -1.87500000e-01, -1.20117188e-01,
        1.55273438e-01, -9.91210938e-02,  1.42578125e-01, -1.64062500e-01,
       -8.93554688e-02,  2.00195312e-01, -1.49414062e-01,  3.20312500e-01,
        3.28125000e-01,  2.44140625e-02, -9.71679688e-02, -8.20312500e-02,
       -3.63769531e-02, -8.59375000e-02, -9.86328125e-02,  7.78198242e-03,
       -1.34277344e-02,  5.27343750e-02,  1.48437500e-01,  3.33984375e-01,
        1.66015625e-02, -2.12890625e-01, -1.50756836e-02,  5.24902344e-02,
       -1.07421875e-01, -8.88671875e-02,  2.49023438e-01, -7.03125000e-02,
       -1.59912109e-02,  7.56835938e-02, -7.03125000e-02,  1.19140625e-01,
        2.29492188e-01,  

In [14]:
dog.shape

(300,)

In [15]:
puppy = model['puppy']
puppy

array([ 0.07177734,  0.11425781, -0.11767578,  0.10205078, -0.07226562,
        0.07373047,  0.20605469,  0.04003906, -0.01525879, -0.03369141,
        0.22460938, -0.35351562, -0.10644531, -0.19921875, -0.02355957,
        0.04785156, -0.2265625 ,  0.28125   , -0.40820312, -0.16796875,
        0.265625  , -0.07373047,  0.28515625, -0.01287842, -0.09716797,
        0.13769531, -0.13769531,  0.28125   ,  0.43164062, -0.13867188,
       -0.09130859, -0.10498047, -0.23046875, -0.13476562, -0.17578125,
        0.00811768,  0.05444336, -0.31640625,  0.18066406,  0.27929688,
       -0.0255127 , -0.29101562,  0.13476562,  0.04418945,  0.09179688,
       -0.05004883,  0.17578125,  0.13574219, -0.15429688,  0.10449219,
        0.00218201,  0.33398438,  0.23339844,  0.0390625 ,  0.08007812,
       -0.04223633,  0.22460938, -0.25195312,  0.28125   , -0.00138092,
        0.14746094,  0.19921875,  0.03613281,  0.234375  , -0.01397705,
       -0.28710938, -0.00224304, -0.12255859, -0.24902344,  0.22

In [16]:
similarity = cosine_similarity(dog.reshape(1,-1),puppy.reshape(1,-1))[0][0]

print("Cosine similarity : ", similarity)

Cosine similarity :  0.8106429


In [17]:
king = model['king']
king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [18]:
similar_words = model.most_similar("king")
similar_words

[('kings', 0.7138045430183411),
 ('queen', 0.6510956883430481),
 ('monarch', 0.6413194537162781),
 ('crown_prince', 0.6204220056533813),
 ('prince', 0.6159993410110474),
 ('sultan', 0.5864824056625366),
 ('ruler', 0.5797567367553711),
 ('princes', 0.5646552443504333),
 ('Prince_Paras', 0.5432944297790527),
 ('throne', 0.5422105193138123)]

In [19]:
# king - man + woman = queen
king = model['king']
man = model['man']
woman = model['woman']
queen = model['queen']

In [20]:
result = king - man + woman

In [21]:
similarity = cosine_similarity(result.reshape(1,-1), queen.reshape(1,-1))[0][0]

print("Cosine similarity : ", similarity)

Cosine similarity :  0.73005176


In [22]:
model.most_similar(positive=['king','woman'],negative=['man'])

[('queen', 0.7118193507194519),
 ('monarch', 0.6189674139022827),
 ('princess', 0.5902431011199951),
 ('crown_prince', 0.5499460697174072),
 ('prince', 0.5377321839332581),
 ('kings', 0.5236844420433044),
 ('Queen_Consort', 0.5235945582389832),
 ('queens', 0.5181134343147278),
 ('sultan', 0.5098593831062317),
 ('monarchy', 0.5087411999702454)]

In [23]:
from gensim.models import Word2Vec

# Define your own corpus as a list of sentences
corpus = [
    ["the", "quick", "brown", "fox", "jumps", "over", "the", "lazy", "dog"],
    ["a", "king", "and", "his", "queen", "rule", "over", "their", "kingdom"],
    ["man", "and", "woman", "walk", "together", "in", "the", "park"],
    ["the", "boy", "plays", "with", "his", "puppy", "in", "the", "yard"]
]

# Train a Word2Vec model on your corpus
model = Word2Vec(corpus, min_count=1)

# Find the words most similar to a given word
similar_words = model.wv.most_similar("king")

# Print the top 10 most similar words and their cosine similarity scores
for word, score in similar_words[:10]:
    print(word, score)

his 0.2531651556491852
with 0.14945608377456665
boy 0.14724946022033691
man 0.14262345433235168
in 0.1377280205488205
kingdom 0.11693627387285233
together 0.07168899476528168
park 0.04576393589377403
queen 0.04498213902115822
yard 0.02727307565510273
